
package gamejam;

import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class Frame extends javax.swing.JFrame {

   
    GameJam game = new GameJam();
    Random rad = new Random();
    Problem theProblem = new Problem(rad.nextInt(2));
    int points =0;
     
            
    
    public Frame() {
        initComponents();
        Problem_Tittle.setText(theProblem.toStrings());
        jButton1.setText(theProblem.getAn1()); 
        jButton2.setText(theProblem.getAn2());
        jButton3.setText(theProblem.getAn3());
        
       whileVisible();
    }

    public void whileVisible(){
        start.setVisible(true);
        email.setVisible(false);
        nameOfEmployee.setVisible(false);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        client.setVisible(false);
        details.setVisible(false);
        Problem_Tittle.setVisible(false);
    }
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        nameOfEmployee = new javax.swing.JLabel();
        client = new javax.swing.JLabel();
        details = new javax.swing.JLabel();
        Problem_Tittle = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        ok = new javax.swing.JLabel();
        start = new javax.swing.JLabel();
        Last = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Answer 1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 730, 40));

        jButton2.setText("Answer 2");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 730, 40));

        jButton3.setText("Answer 3");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 730, 40));

        nameOfEmployee.setBackground(new java.awt.Color(51, 51, 51));
        nameOfEmployee.setFont(new java.awt.Font("Menlo", 0, 20)); // NOI18N
        nameOfEmployee.setForeground(new java.awt.Color(204, 0, 204));
        nameOfEmployee.setText("name");
        nameOfEmployee.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(nameOfEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 180, -1));
        nameOfEmployee.getAccessibleContext().setAccessibleName("noAnActualName");

        getContentPane().add(client, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 156, 160, 160));

        details.setText("detailsssssssssss");
        getContentPane().add(details, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        Problem_Tittle.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        Problem_Tittle.setForeground(new java.awt.Color(223, 183, 33));
        Problem_Tittle.setText("Problem");
        Problem_Tittle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(Problem_Tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 390, 30));

        email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/email.jpg"))); // NOI18N
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        ok.setText(" ");
        ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okMouseClicked(evt);
            }
        });
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/start.png"))); // NOI18N
        start.setText(" ");
        getContentPane().add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 180));

        Last.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desktop.jpg"))); // NOI18N
        getContentPane().add(Last, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        client.setIcon(new ImageIcon("c2.png"));
      
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
       client.setIcon(new ImageIcon("c25.png")); 
    
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
    JOptionPane.showMessageDialog(null, "im dissapointed ", 
                                    "mad boss lol ", 0, 
                                    new ImageIcon("roary.gif"));
    }//GEN-LAST:event_jButton3MouseClicked

    private void okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMouseClicked
       start.setVisible(false);
        email.setVisible(true);
        nameOfEmployee.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(true);
        client.setVisible(true);
        details.setVisible(true);
        Problem_Tittle.setVisible(true);
    }//GEN-LAST:event_okMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frame frame =new Frame();
                frame.setVisible(true);
                frame.setResizable(false);
                
                
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Last;
    private javax.swing.JLabel Problem_Tittle;
    private javax.swing.JLabel client;
    private javax.swing.JLabel details;
    private javax.swing.JLabel email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel nameOfEmployee;
    private javax.swing.JLabel ok;
    private javax.swing.JLabel start;
    // End of variables declaration//GEN-END:variables
}
